stages:
  - test
  - publish

variables:
  # Specifies which version of python to use
  PYTHON_VERSION: "3.7"
  # Sets the requirements file for pip install -r
  REQUIREMENTS_FILE: "requirements.txt"
  # Enables building sphinx odc
  DOC: "true"
  # Additional options to pass to sphinx-build
  DOC_ARGS: "-b html"
  # Relative path to doc source
  DOC_SOURCE: "/builds/flywheel-io/public/flywheel-tutorials/docs/source"

  # This is the relative directory of your python package
  PACKAGE_DIR: $CI_PROJECT_NAME



.python:
  image: python:${PYTHON_VERSION}

  # Change pip's cache directory to be inside the project directory since we can
  # only cache local items.
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    PYTHONUSERBASE: "$CI_PROJECT_DIR/.cache/user-site"

  # Pip's cache doesn't store the python packages
  # Instead we use user-site/ as the user base
  # See: https://pip.readthedocs.io/en/latest/user_guide/#user-installs
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cache/pip
      - .cache/user-site/

  before_script:
  - export PATH="$PATH:$PYTHONUSERBASE/bin"
  - mkdir -p .cache/user-site/
  - python -V
  - pip install nbconvert


test:convert:
  extends: .python
  stage: test
  script:
    - cd /builds/flywheel-io/public/flywheel-tutorials/python
    - for FILE in *.ipynb; do jupyter nbconvert --output-dir='../docs' --to html $FILE; done
  artifacts:
    paths:
      - /builds/flywheel-io/public/flywheel-tutorials/docs


publish:convert:
  extends: .python
  stage: publish
  script:
    - cd /builds/flywheel-io/public/flywheel-tutorials/python
    - for FILE in *.ipynb; do jupyter nbconvert --output-dir='../docs' --to html $FILE; done
  artifacts:
    paths:
      - /builds/flywheel-io/public/flywheel-tutorials/docs


# Build the doc and save artifacts
pages:
  stage: publish
  only:
    variables:
      - $DOC == "true"
  script:
    - mv /builds/flywheel-io/public/flywheel-tutorials/docs/TOC.html /builds/flywheel-io/public/flywheel-tutorials
    - mv TOC.html index.html
    - cd /builds/flywheel-io/public/flywheel-tutorials
    - mkdir .public
    - cp -r /builds/flywheel-io/public/flywheel-tutorials/docs .public
    - mv .public public

  artifacts:
    paths:
      - public
  only:
  - master