stages:
  - publish
  - deploy

variables:
  # Specifies which version of python to use
  PYTHON_VERSION: "3.7"
  # This is the relative directory of your python package
  PACKAGE_DIR: $CI_PROJECT_NAME

.python:
  image: python:${PYTHON_VERSION}

  # Change pip's cache directory to be inside the project directory since we can
  # only cache local items.
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    PYTHONUSERBASE: "$CI_PROJECT_DIR/.cache/user-site"

  # Pip's cache doesn't store the python packages
  # Instead we use user-site/ as the user base
  # See: https://pip.readthedocs.io/en/latest/user_guide/#user-installs
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cache/pip
      - .cache/user-site/

  before_script:
  - export PATH="$PATH:$PYTHONUSERBASE/bin"
  - mkdir -p .cache/user-site/
  - python -V
  - pip install nbconvert
  - pip install requests==2.7.0

pages:
  extends: .python
  stage: publish
  only:
    refs:
      - master
  script:
    - cd $CI_PROJECT_DIR
    - mkdir public
    - |
      for FILE in ${CI_PROJECT_DIR}/python/*.ipynb; do 
        jupyter nbconvert --output-dir=${CI_PROJECT_DIR}/public --to html $FILE; 
        echo "File $FILE converted"
      done
    - mv public/TOC.html public/tmp.html
    - cat public/tmp.html | sed 's_gitlab.com/flywheel-io/public/flywheel-tutorials/-/blob/master/python_flywheel-io.gitlab.io/public/flywheel-tutorials_g;s/.ipynb/.html/g' > public/index.html
    - rm public/tmp.html
    - ls public/
  artifacts:
    paths:
      - public

deploy:publish_article:
  extends: .python
  stage: deploy
  only:
    refs:
      - master
  script:
    - sleep 3m
    - python3 ${CI_PROJECT_DIR}/.script/zd_article_setup.py
  artifacts:
    paths:
      - public
