stages:
  - test
  - publish

variables:
  # Specifies which version of python to use
  PYTHON_VERSION: "3.7"
  # Sets the requirements file for pip install -r
  REQUIREMENTS_FILE: "requirements.txt"
  # Enables building sphinx odc
  DOC: "true"
  # Additional options to pass to sphinx-build
  DOC_ARGS: "-b html"
  # Relative path to doc source
  DOC_SOURCE: "docs/source"


.python:
  image: python:${PYTHON_VERSION}

  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    PYTHONUSERBASE: "$CI_PROJECT_DIR/.cache/user-site"


  before_script:
    - export PATH="$PATH:$PYTHONUSERBASE/bin"
    - python -V
    - pip install --user jupyter notebook 
    - pip install --user nbconvert




test:convert:
  extends: .python
  stage: test
  script:
    - cd ./python
    - for FILE in *.ipynb; do jupyter nbconvert --output-dir='../docs' --to html $FILE; done
  artifacts:
    paths:
      - ../doc

# Build the doc and save artifacts
test:doc:
  extends: .python
  stage: test
  only:
    variables:
      - $DOC == "true"
  script:
    - sphinx-build $DOC_ARGS $DOC_SOURCE doc
  artifacts:
    paths:
      - doc
